=== Belloxy/AionEncomBase/data/static_data/custom_pvp/archsoft_pvp/pvp_event_data.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:include schemaLocation="../import.xsd" />
    <xs:element name="pvp_event_data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="event_type" type="PvPEventType" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="PvPEventType">
        <xs:sequence>
            <xs:element name="portal_data" type="PvPPortalData" minOccurs="1" maxOccurs="1"/>
            <xs:element name="schedule_data" type="PvPScheduleData" minOccurs="1" maxOccurs="1"/>    
			<xs:element name="kill_series" type="PvPEventKillSeriesData" minOccurs="1" maxOccurs="1"/> 			
        </xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required"/>
		<xs:attribute name="pvp_name" type="xs:string" use="optional"/>			
    </xs:complexType>      
    <xs:complexType name="PvPPortalData">
        <xs:sequence>
            <xs:element name="portal_loc" type="PvPPortalLoc" minOccurs="1" maxOccurs="unbounded"/>	
        </xs:sequence>     
		<xs:attribute name="cooldown" type="xs:int" use="optional"/>
		<xs:attribute name="always_spawn" type="xs:boolean" use="optional"/>			
    </xs:complexType> 
    <xs:complexType name="PvPPortalLoc">    
        <xs:attribute name="portal_type" type="PvPPortalType" use="optional"/>
		<xs:attribute name="portal_master_name" type="xs:string" use="optional"/>
		<xs:attribute name="portal_ai" type="xs:string" use="optional"/>
		<xs:attribute name="race" type="xs:string" use="optional"/>
		<xs:attribute name="npc_id" type="xs:int" use="optional"/>
		<xs:attribute name="map_id" type="xs:int" use="optional"/>
		<xs:attribute name="x" type="xs:float" use="optional"/>
        <xs:attribute name="y" type="xs:float" use="optional"/>        
        <xs:attribute name="z" type="xs:float" use="optional"/>
        <xs:attribute name="h" type="xs:byte" use="optional"/>
    </xs:complexType>  
    <xs:complexType name="PvPScheduleData">
		<xs:sequence>
			<xs:element name="event_data" type="PvPEventData" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence> 
    </xs:complexType>
    <xs:complexType name="PvPEventData">
        <xs:sequence>
            <xs:element name="spawn_loc" type="PvPSpawnLoc" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="reward_data" type="PvPRewardData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="mob_spawn" type="PvPEventMobSpawnData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="start_condition" type="PvPEventStartCondition" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>     
		<xs:attribute name="day_time" type="xs:string" use="optional"/>
		<xs:attribute name="battle_time" type="xs:int" use="optional"/>
		<xs:attribute name="waiting_time" type="xs:int" use="optional"/>
		<xs:attribute name="world_type" type="xs:string" use="optional"/>
		<xs:attribute name="win_condition_kills" type="xs:int" use="optional"/>
		<xs:attribute name="win_condition_points" type="xs:int" use="optional"/>
    </xs:complexType>  
    <xs:complexType name="PvPSpawnLoc">
        <xs:attribute name="x" type="xs:float" use="optional"/>
        <xs:attribute name="y" type="xs:float" use="optional"/>        
        <xs:attribute name="z" type="xs:float" use="optional"/>
        <xs:attribute name="h" type="xs:byte" use="optional"/>
    </xs:complexType> 
	<xs:complexType name="PvPRewardData">
        <xs:attribute name="rank" type="xs:int" use="optional"/>
		<xs:attribute name="kills" type="xs:int" use="optional"/>
		<xs:attribute name="points" type="xs:int" use="optional"/>
        <xs:attribute name="item_list" type="xs:string" use="optional"/>        
        <xs:attribute name="ap" type="xs:int" use="optional"/>
        <xs:attribute name="gp" type="xs:int" use="optional"/>
		<xs:attribute name="gc" type="xs:int" use="optional"/>
		<xs:attribute name="kinah" type="xs:int" use="optional"/>
    </xs:complexType>
	<xs:complexType name="PvPEventMobSpawnData">
		<xs:sequence>
			<xs:element name="mob_spawn_loc" type="PvPEventMobSpawnList" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence> 
    </xs:complexType>
	<xs:complexType name="PvPEventMobSpawnList">
		<xs:attribute name="npc_id" type="xs:int" use="optional"/>
        <xs:attribute name="x" type="xs:float" use="optional"/>
		<xs:attribute name="y" type="xs:float" use="optional"/>        
		<xs:attribute name="z" type="xs:float" use="optional"/>
		<xs:attribute name="h" type="xs:byte" use="optional"/>
		<xs:attribute name="kill_point" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="defense_point" type="xs:int" use="optional" default="0"/> 
		<xs:attribute name="respawn" type="xs:int" use="optional" default="0"/> 		
    </xs:complexType> 
	<xs:complexType name="PvPEventStartCondition">
        <xs:sequence>
            <xs:element name="single_players_to_start" type="xs:int" minOccurs="0" maxOccurs="1" default="0"/>
            <xs:element name="groups_to_start" type="xs:int" minOccurs="0" maxOccurs="1" default="0"/>
            <xs:element name="players_for_each_group_to_start" type="xs:int" minOccurs="0" maxOccurs="1" default="0"/>
        </xs:sequence>     
    </xs:complexType> 
	<xs:complexType name="PvPEventKillSeriesData">
		<xs:sequence>
			<xs:element name="kill_list" type="PvPEventKillList" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence> 
    </xs:complexType>
	<xs:complexType name="PvPEventKillList">
		<xs:attribute name="count_kill" type="xs:int" use="optional"/>
        <xs:attribute name="title_kills" type="xs:string" use="optional"/>
		<xs:attribute name="reward_item_list" type="xs:string" use="optional"/>        
		<xs:attribute name="ap" type="xs:int" use="optional"/>
		<xs:attribute name="gp" type="xs:int" use="optional"/>
		<xs:attribute name="kinah" type="xs:int" use="optional"/>   
    </xs:complexType> 
    <xs:simpleType name="PvPPortalType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="HUMAN"/>		
        </xs:restriction>
    </xs:simpleType> 
</xs:schema>

=== Belloxy/AionEncomBase/data/static_data/custom_pvp/archsoft_pvp/pvp_event_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<pvp_event_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pvp_event_data.xsd">
	<event_type type="PVPALLENEMY" pvp_name="PvP All Enemy">
		<portal_data cooldown="300" always_spawn="true">
			<portal_loc portal_type="HUMAN" portal_master_name="PvP All Enemy" portal_ai="PortalPvPCustom" race="ASMODIANS" npc_id="806080" map_id="120010000" x="1600.5948" y="1400.6274" z="193.12746" h="119"/>
			<portal_loc portal_type="HUMAN" portal_master_name="" portal_ai="general" race="ASMODIANS" npc_id="281446" map_id="120010000" x="1600.5948" y="1400.6274" z="193.12746" h="119"/>
			<portal_loc portal_type="HUMAN" portal_master_name="PvP All Enemy" portal_ai="PortalPvPCustom" race="ELYOS" npc_id="806076" map_id="110010000" x="1448.9688" y="1511.088" z="573.0719" h="60"/>
			<portal_loc portal_type="HUMAN" portal_master_name="" portal_ai="general" race="ELYOS" npc_id="281448" map_id="110010000" x="1448.9688" y="1511.088" z="573.0719" h="60"/>
		</portal_data>
		<schedule_data>
			<event_data day_time="* * 0,1,2,3,4,6,8,9,10,12,14,16,18,20,22 ? * FRI *" battle_time="60" world_type="RENTUS_BASE" win_condition_kills="30">
				<spawn_loc x="239.82019" y="604.7481" z="178.47974" h="60"/>
				<spawn_loc x="277.6929" y="740.7806" z="163.62155" h="60"/>
				<spawn_loc x="341.15125" y="588.58734" z="145.875" h="60"/>
				<spawn_loc x="421.63766" y="502.11075" z="138.625" h="60"/>
				<spawn_loc x="366.25186" y="466.01166" z="138.64696" h="60"/>
				<spawn_loc x="429.19247" y="435.33118" z=" 149.49472" h="60"/>
				<spawn_loc x="481.72885" y="557.62854" z="147.14131" h="60"/>
				<spawn_loc x="552.6186" y="570.0499" z="153.19925" h="60"/>
				<spawn_loc x="460.748" y="532.22766" z="139.45325" h="60"/>
				<reward_data rank="1" item_list="186000242:10" ap="100000" gp="5000" kinah="10000000"/>
				<reward_data rank="2" item_list="186000242:5" ap="100000" gp="2000" kinah="10000000"/>
				<reward_data rank="3" item_list="186000242:2" ap="100000" gp="1000" kinah="10000000"/>
			</event_data>
			<event_data day_time="* * 1,3,5,7,9,11,13,15,17,19,21,23 ? * FRI *" battle_time="60" world_type="LF6" win_condition_kills="30">
				<spawn_loc x="95.90935" y="2885.264" z="319.0278" h="60"/>
				<spawn_loc x="224.45291" y="2901.876" z="299.00775" h="60"/>
				<spawn_loc x="293.4441" y="2783.8098" z="295.0" h="60"/>
				<spawn_loc x="585.7756" y="2884.7014" z="269.38904" h="60"/>
				<spawn_loc x="575.8468" y="2676.736" z="287.16144" h="60"/>
				<spawn_loc x="545.01575" y="2515.9128" z="300.17758" h="60"/>
				<spawn_loc x="679.882" y="2525.284" z="294.1324" h="60"/>
				<spawn_loc x="698.6583" y="2671.336" z="297.25702" h="60"/>
				<spawn_loc x="684.40936" y="2823.7659" z="299.0" h="60"/>
				<spawn_loc x="361.03583" y="2645.163" z="288.75" h="60"/>
				<reward_data rank="1" item_list="186000242:10" ap="100000" gp="5000" kinah="10000000"/>
				<reward_data rank="2" item_list="186000242:5" ap="100000" gp="2000" kinah="10000000"/>
				<reward_data rank="3" item_list="186000242:2" ap="100000" gp="1000" kinah="10000000"/>
			</event_data>
		</schedule_data>
		<kill_series>
			<kill_list count_kill="5" title_kills="Killing Spree" reward_item_list="186000242:1" ap="100000" gp="1000" kinah="1000000"/>
			<kill_list count_kill="10" title_kills="Dominating" reward_item_list="186000242:2" ap="100000" gp="1500" kinah="1000000"/>
			<kill_list count_kill="15" title_kills="Mega Kill" reward_item_list="186000242:3" ap="100000" gp="2000" kinah="1000000"/>
			<kill_list count_kill="20" title_kills="Unstoppable!" reward_item_list="186000242:4" ap="100000" gp="2500" kinah="1000000"/>
			<kill_list count_kill="40" title_kills="Wicked Sick" reward_item_list="186000242:5" ap="100000" gp="3000" kinah="1000000"/>
			<kill_list count_kill="60" title_kills="Monster Kill!!!" reward_item_list="186000242:6" ap="100000" gp="3500" kinah="1000000"/>
			<kill_list count_kill="80" title_kills="Godlike!" reward_item_list="186000242:7" ap="100000" gp="4000" kinah="1000000"/>
			<kill_list count_kill="100" title_kills="Beyond Godlike!" reward_item_list="186000242:8" ap="100000" gp="5000" kinah="1000000"/>
		</kill_series>
	</event_type>
	<event_type type="PVPVEMIX" pvp_name="PvPvE Mix Fight">
		<portal_data cooldown="300" always_spawn="true">
			<portal_loc portal_type="HUMAN" portal_master_name="PvPvE Mix Fight" portal_ai="PortalPvPCustom" race="ASMODIANS" npc_id="749132" map_id="120010000" x="1580.8129" y="1406.4113" z="193.1057" h="1"/>
			<portal_loc portal_type="HUMAN" portal_master_name="PvPvE Mix Fight" portal_ai="PortalPvPCustom" race="ELYOS" npc_id="749132" map_id="110010000" x="1453.6718" y="1520.5443" z="573.0719" h="60"/>
		</portal_data>
		<schedule_data>
			<event_data day_time="* 59/60 * ? * * *" battle_time="60" world_type="IRON_WALL_WARFRONT" win_condition_kills="100">
				<spawn_loc x="606.68677" y="896.3561" z="195.53622" h="90"/>
				<spawn_loc x="590.2951" y="505.4177" z="217.76854" h="31"/>
				<spawn_loc x="449.29" y="448.44376" z="270.74738" h="69"/>
				<spawn_loc x="340.78583" y="622.3965" z="246.97649" h="44"/>
				<spawn_loc x="483.52164" y="668.2058" z="221.4411" h="30"/>
				<spawn_loc x="422.03656" y="771.27795" z="205.1365" h="1"/>
				<spawn_loc x="711.93744" y="324.7437" z="252.13892" h="43"/>
				<reward_data rank="1" item_list="186000242:10,186000454:3" ap="100000" gp="10000" kinah="100000000"/>
				<reward_data rank="2" item_list="186000242:5,186000454:2" ap="75000" gp="5000" kinah="100000000"/>
				<reward_data rank="3" item_list="186000242:2,186000454:1" ap="50000" gp="2500" kinah="100000000"/>
				<mob_spawn>
					 <mob_spawn_loc npc_id="241544" x="779.14056" y="316.14203" z="253.43394" h="75" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="241544" x="786.1207" y="322.9532" z="253.43387" h="25" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="241544" x="779.3491" y="331.62335" z="253.43387" h="42" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="241544" x="771.66846" y="325.6246" z="253.43396" h="42" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="241544" x="762.10626" y="337.75443" z="253.43216" h="61" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="241544" x="762.4768" y="331.4081" z="253.43555" h="61" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="241544" x="744.618" y="322.22668" z="249.28627" h="45" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="242344" x="737.9696" y="331.89713" z="249.30327" h="45" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="242344" x="729.86975" y="339.21646" z="249.30322" h="45" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="242344" x="718.0445" y="339.27298" z="249.30322" h="59" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="242344" x="718.66956" y="330.84006" z="252.13892" h="105" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="242344" x="712.351" y="324.21402" z="252.13892" h="105" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="242344" x="707.11975" y="318.15564" z="252.13892" h="105" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="242344" x="698.7583" y="313.45074" z="249.30322" h="69" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="242344" x="704.6775" y="304.2514" z="249.30322" h="101" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="242344" x="711.5123" y="293.61566" z="249.28789" h="98" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="220434" x="697.1634" y="288.9383" z="253.41502" h="71" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="220434" x="698.8096" y="278.65054" z="253.43628" h="93" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="220434" x="707.0762" y="270.049" z="253.43399" h="104" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="220434" x="701.9825" y="263.35474" z="253.43391" h="76" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="220434" x="703.43005" y="252.38664" z="253.72318" h="93" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="220434" x="714.83813" y="252.48384" z="253.434" h="1" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="220434" x="722.42584" y="252.94052" z="253.43416" h="119" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="220434" x="730.5899" y="250.2392" z="253.43427" h="108" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="220434" x="735.4507" y="253.90742" z="253.43428" h="23" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="220434" x="747.60187" y="266.3026" z="252.19843" h="12" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="220434" x="641.25146" y="414.55902" z="243.93753" h="14" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="220434" x="650.5015" y="404.78217" z="240.32068" h="104" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="244470" x="652.36163" y="393.5278" z="240.22342" h="92" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="244470" x="664.1436" y="393.53088" z="240.22342" h="116" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="244470" x="671.6387" y="382.13937" z="241.59521" h="116" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="244470" x="670.3937" y="372.35596" z="241.71388" h="83" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="244470" x="662.89844" y="363.01617" z="241.59521" h="68" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="244470" x="650.52594" y="356.80164" z="241.59521" h="74" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="244470" x="697.2158" y="392.48358" z="241.90862" h="16" kill_point="100" respawn="120"/>
					 <mob_spawn_loc npc_id="244470" x="706.1573" y="388.57983" z="243.35422" h="106" kill_point="100" respawn="120"/>
